Test create release branch

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -33,33 +33,36 @@ jobs:
       - name: Checkout reference to have a local copy
         run: git -c advice.detachedHead=false checkout ${{ github.event.inputs.commit-hash-branch }}
 
-      - name: Checkout Master and merge reference with default commit message
-        run: | 
-          git checkout master
-          git merge ${{ github.event.inputs.commit-hash-branch }} --strategy-option theirs --no-edit
+      - name: Create release branch
+        run:  git checkout -b release/v${{ github.event.inputs.release-version }}
 
-      - name: Update versions on poms and commit(If the version is the same with what is already in the pom the build will fail)
-        run: |
-          mvn versions:set -DnewVersion=${{ github.event.inputs.release-version }} -DgenerateBackupPoms=false --quiet
-          find . -name 'pom.xml' | xargs git add
-          git commit -m "Set release version ${{ github.event.inputs.release-version }}"
-
-      - name: Tag commit with provided version and push
-        run: |
-          git tag v${{ github.event.inputs.release-version }}
-          git push
-          git push origin v${{ github.event.inputs.release-version }}      
-
-      - name: Generate changelog between last two release tags (v*)
-        run: |
-          VERSIONS_RANGE=`git tag --sort=-creatordate  | head -2 | tail -1`..`git tag --sort=-creatordate | head -1`
-          echo "VERSIONS_RANGE: ${VERSIONS_RANGE}"
-          git log --pretty="%s" ${VERSIONS_RANGE} > changelog.txt
-
-      - name: Create Github release Release
-        uses: ncipollo/release-action@v1
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          bodyFile: "changelog.txt"
-          tag: v${{ github.event.inputs.release-version }}
-          draft: true
+#      - name: Checkout Master and merge reference with default commit message
+#        run: |
+#          git checkout master
+#          git merge ${{ github.event.inputs.commit-hash-branch }} --strategy-option theirs --no-edit
+#
+#      - name: Update versions on poms and commit(If the version is the same with what is already in the pom the build will fail)
+#        run: |
+#          mvn versions:set -DnewVersion=${{ github.event.inputs.release-version }} -DgenerateBackupPoms=false --quiet
+#          find . -name 'pom.xml' | xargs git add
+#          git commit -m "Set release version ${{ github.event.inputs.release-version }}"
+#
+#      - name: Tag commit with provided version and push
+#        run: |
+#          git tag v${{ github.event.inputs.release-version }}
+#          git push
+#          git push origin v${{ github.event.inputs.release-version }}
+#
+#      - name: Generate changelog between last two release tags (v*)
+#        run: |
+#          VERSIONS_RANGE=`git tag --sort=-creatordate  | head -2 | tail -1`..`git tag --sort=-creatordate | head -1`
+#          echo "VERSIONS_RANGE: ${VERSIONS_RANGE}"
+#          git log --pretty="%s" ${VERSIONS_RANGE} > changelog.txt
+#
+#      - name: Create Github release Release
+#        uses: ncipollo/release-action@v1
+#        with:
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          bodyFile: "changelog.txt"
+#          tag: v${{ github.event.inputs.release-version }}
+#          draft: true
