Test release

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -29,24 +29,24 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
-      - name: Checkout code
+      - name: Checkout code (source)
         uses: actions/checkout@v3
         with:
           fetch-depth: 0
           # USE PERSONAL ACCESS TOKEN instead of the default to allow triggering CI workflow
           token: ${{ secrets.METIS_PERSONAL_ACCESS_TOKEN }}
-          ref: ${{ github.event.inputs.target-merge-branch }}
+          ref: ${{ inputs.commit-hash-branch }}
 
       - name: Setup git config
         run: |
           git config user.name 'github-actions[bot]'
           git config user.email 'github-actions[bot]@users.noreply.github.com'
 
-      - name: Checkout reference to have a local copy
-        run: git -c advice.detachedHead=false checkout ${{ github.event.inputs.commit-hash-branch }}
+#      - name: Checkout reference to have a local copy
+#        run: git -c advice.detachedHead=false checkout ${{ github.event.inputs.commit-hash-branch }}
 
       - name: Create release branch
-        run: git checkout -b release/v${{ github.event.inputs.release-version }}
+        run: git checkout -b release/v${{ inputs.release-version }}
 
       - name: Update versions on poms(release) and commit(If the version is the same with what is already in the pom the build will fail)
         run: |
@@ -55,66 +55,66 @@ jobs:
           git commit -m "Set release version ${{ github.event.inputs.release-version }}"
 
       - name: Push release branch
-        run: git push -u origin release/v${{ github.event.inputs.release-version }}
-
-      - name: Checkout Master and merge reference with default commit message
-        # --strategy-option theirs is added for the case where the version is updated on both branches(could potential be removed)
-        run: |
-          git checkout ${{ github.event.inputs.target-merge-branch }}
-          git merge release/v${{ github.event.inputs.release-version }} --strategy-option theirs --no-edit
-
-      - name: Tag commit with provided version and push
-        run: |
-          git tag v${{ github.event.inputs.release-version }}
-          git push
-          git push origin v${{ github.event.inputs.release-version }}
-
-      - name: Generate changelog between last two release tags (v*)
-        run: |
-          VERSIONS_RANGE=`git tag --sort=-creatordate  | head -2 | tail -1`..`git tag --sort=-creatordate | head -1`
-          echo "VERSIONS_RANGE: ${VERSIONS_RANGE}"
-          git log --pretty="%s" ${VERSIONS_RANGE} > changelog.txt
-
-      - name: Curate changelog to releaselog
-        run: |
-          grep -i '^feat\|feature' changelog.txt > feature.txt || true
-          grep -i '^debt' changelog.txt > debt.txt || true
-          grep -i '^bug' changelog.txt > bug.txt || true
-          grep -i -v '^feat\|feature\|debt\|bug' changelog.txt > miscellaneous.txt || true
-          
-          echo -e "FEATURES:" >> releaselog.txt
-          cat feature.txt >> releaselog.txt
-          echo -e >> releaselog.txt
-          
-          echo -e "DEBT:" >> releaselog.txt
-          cat debt.txt >> releaselog.txt
-          echo -e >> releaselog.txt
-          
-          echo -e "BUGS:" >> releaselog.txt
-          cat bug.txt >> releaselog.txt
-          echo -e >> releaselog.txt
-          
-          echo -e "MISCELLANEOUS:" >> releaselog.txt
-          cat miscellaneous.txt >> releaselog.txt
-          echo -e >> releaselog.txt
-          cat releaselog.txt
-
-      - name: Create Github release
-        uses: ncipollo/release-action@v1
-        with:
-          token: ${{ secrets.GITHUB_TOKEN }}
-          bodyFile: "releaselog.txt"
-          tag: v${{ github.event.inputs.release-version }}
-          draft: true
-
-      - name: Checkout reference
-        run: git -c advice.detachedHead=false checkout ${{ github.event.inputs.commit-hash-branch }}
-
-      - name: Update versions on poms(reference) and commit(If the version is the same with what is already in the pom the build will fail)
-        run: |
-          mvn versions:set -DnewVersion=${{ github.event.inputs.new-snapshot-version }} -DgenerateBackupPoms=false --quiet
-          find . -name 'pom.xml' | xargs git add
-          git commit -m "Set new snapshot version ${{ github.event.inputs.new-snapshot-version }}"
-
-      - name: Push updated reference
-        run: git push origin ${{ github.event.inputs.commit-hash-branch }}
+        run: git push -u origin release/v${{ inputs.release-version }}
+#
+#      - name: Checkout Master and merge reference with default commit message
+#        # --strategy-option theirs is added for the case where the version is updated on both branches(could potential be removed)
+#        run: |
+#          git checkout ${{ github.event.inputs.target-merge-branch }}
+#          git merge release/v${{ github.event.inputs.release-version }} --strategy-option theirs --no-edit
+#
+#      - name: Tag commit with provided version and push
+#        run: |
+#          git tag v${{ github.event.inputs.release-version }}
+#          git push
+#          git push origin v${{ github.event.inputs.release-version }}
+#
+#      - name: Generate changelog between last two release tags (v*)
+#        run: |
+#          VERSIONS_RANGE=`git tag --sort=-creatordate  | head -2 | tail -1`..`git tag --sort=-creatordate | head -1`
+#          echo "VERSIONS_RANGE: ${VERSIONS_RANGE}"
+#          git log --pretty="%s" ${VERSIONS_RANGE} > changelog.txt
+#
+#      - name: Curate changelog to releaselog
+#        run: |
+#          grep -i '^feat\|feature' changelog.txt > feature.txt || true
+#          grep -i '^debt' changelog.txt > debt.txt || true
+#          grep -i '^bug' changelog.txt > bug.txt || true
+#          grep -i -v '^feat\|feature\|debt\|bug' changelog.txt > miscellaneous.txt || true
+#
+#          echo -e "FEATURES:" >> releaselog.txt
+#          cat feature.txt >> releaselog.txt
+#          echo -e >> releaselog.txt
+#
+#          echo -e "DEBT:" >> releaselog.txt
+#          cat debt.txt >> releaselog.txt
+#          echo -e >> releaselog.txt
+#
+#          echo -e "BUGS:" >> releaselog.txt
+#          cat bug.txt >> releaselog.txt
+#          echo -e >> releaselog.txt
+#
+#          echo -e "MISCELLANEOUS:" >> releaselog.txt
+#          cat miscellaneous.txt >> releaselog.txt
+#          echo -e >> releaselog.txt
+#          cat releaselog.txt
+#
+#      - name: Create Github release
+#        uses: ncipollo/release-action@v1
+#        with:
+#          token: ${{ secrets.GITHUB_TOKEN }}
+#          bodyFile: "releaselog.txt"
+#          tag: v${{ github.event.inputs.release-version }}
+#          draft: true
+#
+#      - name: Checkout reference
+#        run: git -c advice.detachedHead=false checkout ${{ github.event.inputs.commit-hash-branch }}
+#
+#      - name: Update versions on poms(reference) and commit(If the version is the same with what is already in the pom the build will fail)
+#        run: |
+#          mvn versions:set -DnewVersion=${{ github.event.inputs.new-snapshot-version }} -DgenerateBackupPoms=false --quiet
+#          find . -name 'pom.xml' | xargs git add
+#          git commit -m "Set new snapshot version ${{ github.event.inputs.new-snapshot-version }}"
+#
+#      - name: Push updated reference
+#        run: git push origin ${{ github.event.inputs.commit-hash-branch }}
